FROM node:20-alpine

WORKDIR /app

# Copia arquivos de dependência
COPY package*.json ./

# Instala dependências
RUN npm install

# Copia o restante do código da API
COPY . .

# Expõe a porta 3000
EXPOSE 3000

# Comando para iniciar a API
CMD ["node", "server-api.js"]
